bitakora/base/urls.py
from django.conf.urls import url, include
from bitakora.rss.feeds import BlogEntriesFeed
from django.views.generic.base import RedirectView
from bitakora.contact.views import BitakoraContactFormView, BlogContactDetailView
from bitakora.base import views


urlpatterns = [
    url(r'^new-blog$', views.new_blog, name='new_blog'),
    url(r'^new-blog/import$', views.import_blog, name='import_blog'),
    url(r'^schools/', include('bitakora.ikasbloga.urls')),

    url(r'^change_comment_status$', views.change_comment_status, name='change_comment_status'),
    url(r'^(?P<slug>[\-\d\w]+)$', views.blog_index, name='blog_index'),
    url(r'^(?P<slug>[\-\d\w]+)/archive$', views.blog_archive, name='blog_archive'),
    url(r'^(?P<slug>[\-\d\w]+)/my-posts$', views.my_posts, name='my_posts'),
    url(r'^(?P<slug>[\-\d\w]+)/my_comments$', views.my_comments, name='my_comments'),
    url(r'^(?P<slug>[\-\d\w]+)/export$', views.export_blog, name='export_blog'),
    url(r'^(?P<slug>[\-\d\w]+)/contact$', BitakoraContactFormView.as_view(
        template_name='contact/blog_contact_form.html'),
        name='blog_contact_form'),
    url(r'^(?P<slug>[\-\d\w]+)/contact-sent$', BlogContactDetailView.as_view(
        template_name='contact/blog_contact_form_sent.html'),
        name='blog_contact_form_sent'),

    url(r'^(?P<blogslug>[\-\d\w]+)/add-article$', views.add_article, name='add_article'),
    # url(r'^(?P<blogslug>[\-\d\w]+)/rss$', BlogEntriesFeed(), name="blog_rss"),
    url(r'^(?P<blogslug>[\-\d\w]+)/rss$', RedirectView.as_view(pattern_name='blog_rss')),
    url(r'^(?P<blogslug>[\-\d\w]+)/feed.xml$', BlogEntriesFeed(), name="blog_rss"),
    url(r'^(?P<blogslug>[\-\d\w]+)/(?P<slug>[\-\d\w]+)$', views.article, name='article'),
    url(r'^(?P<blogslug>[\-\d\w]+)/(?P<slug>[\-\d\w]+)/edit-article$', views.edit_article, name='edit_article'),
    url(r'^(?P<blogslug>[\-\d\w]+)/(?P<slug>[\-\d\w]+)/delete-article$', views.delete_article, name='delete_article'),
    url(r'^(?P<blogslug>[\-\d\w]+)/(?P<slug>[\-\d\w]+)/add-comment$', views.add_comment, name='add_comment'),
]

bitakora/urls.py
from django.conf.urls import url, include
from django.http import HttpResponse
from django.views.generic.base import RedirectView
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from bitakora.views import DataGetCategories
from bitakora.base.models import Article
from voting.views import vote_on_object
from django.contrib.flatpages import views as flatpage_views
from bitakora import views
from bitakora.accounts import views as accounts_views
from bitakora.ikasbloga import views as ikasbloga_views
from django.contrib.auth import views as auth_views
from bitakora.accounts.views import BlogRegistrationView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

article_dict = {
    'model': Article,
    'template_object_name': 'article',
}


urlpatterns = [
    url(r'^$', views.index),
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: ", content_type="text/plain")),
    url(r'^category/(?P<slug>[\-\d\w]+)$', views.category, name='category'),
    url(r'^top_stories$', views.top_stories, name='top_stories'),
    url(r'^bookmarks$', views.bookmarks, name='bookmarks'),
    # url(r'^users$', auth_views.login, name='erabiltzailea_user_login'),
    # url(r'^users/password/change/$', accounts_views.edit_pass, name='pasahitza_aldatu'),
    # url(r'^users/password/change/done/$', accounts_views.pass_done, name='pasahitza_aldatuta'),
    url(r'^users/', include('registration.backends.default.urls')),
    url(r'^register/$', BlogRegistrationView.as_view(), name='registration_register'),
    url(r'^users/register/student$', accounts_views.student_registration, name='student_registration'),
    url(r'^users/register/teacher$', accounts_views.teacher_registration, name='teacher_registration'),
    url(r'^users/select-register$', accounts_views.select_register, name='select_register'),
    url(r'^users/useroptions$', views.useroptions, name='useroptions'),
    url(r'^users/edit-profile$', accounts_views.edit_profile, name='edit_profile'),
    url(r'^users/edit-blog$', accounts_views.edit_blog, name='edit_blog'),
    url(r'^users/edit-school$', ikasbloga_views.edit_school, name='edit_school'),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/users/edit-profile', permanent=False), name='users_profile'),
    url(r'^ikasblogak', include('bitakora.ikasbloga.urls')),
    url(r'^ikasblogak/info$', flatpage_views.flatpage, {'url': '/ikasblogak/info/'}, name='ikasblogak_info'),
    url(r'^voting/(?P<object_id>\d+)/(?P<direction>up|down|clear)?$', vote_on_object, article_dict, name="vote_on_object"),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),

    url(r'^ajax/get_categories$', DataGetCategories.as_view(), name='get_categories'),

    url(r'^tinymce/', include('tinymce.urls')),

    url(r'^search/', include('haystack.urls')),

    url(r'^about$', flatpage_views.flatpage, {'url': '/about/'}, name='about'),
    url(r'^contact/', include('contact_form.urls')),

    url(r'^admin/', admin.site.urls),

    url(r'^ajax/categories/', views.get_categories, name='ajax_categories'),
    url(r'^ajax/related_posts/', views.get_related_posts, name='ajax_related_posts'),
    url(r'^ajax/remove_link/', views.remove_link, name='ajax_remove_link'),

    url(r'^', include('bitakora.base.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bitakora/base/models.py
import time
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.db.models.signals import post_save
from django.http import HttpResponseRedirect
from photologue.models import Photo
from django.contrib.sites.models import Site
from bitakora.base.managers import PublishedManager
from bitakora.utils.models import get_user_model_name
from bitakora.utils.text import make_responsive
from bitakora.utils.images import get_pattern
from django.utils.translation import ugettext_lazy as _
from datetime import datetime
from django.template.defaultfilters import striptags, truncatechars
from voting.models import Vote
from django.contrib.contenttypes.models import ContentType
from django.template.loader import get_template
from django.template import Context
from django.core.mail import send_mail
from bitakora.ikasbloga.models import Room

try:
    from django.utils.timezone import now
except ImportError:
    now = datetime.now

user_model_name = get_user_model_name()

DEFAULT_TEMPLATE = "one-page-wonder.css"

TEMPLATE_CHOICES = (
    (DEFAULT_TEMPLATE, _("One page wonder")),
    ("minimalist-blog.css", _("Minimalist")),
)

DEFAULT_LICENSE = "cc-by-sa"

LICENSE_CHOICES = (
    (DEFAULT_LICENSE, _("CC-BY-SA")),
    ("copyright", _("Copyright")),
)

BLOG_PHOTO_SLUG = getattr(settings, 'BLOG_PHOTO_DEFAULT_SLUG', 'no-blog-photo')


class Blog(models.Model):
    name = models.CharField(max_length=200, verbose_name=_('Name'))
    slug = models.SlugField(_("URL"), max_length=300, blank=True, null=True,
            help_text=_("Leave blank to have the URL auto-generated from "
                        "the title."))
    tagline = models.CharField(max_length=200, verbose_name=_('Tagline'), null=True, blank=True)
    header_image = models.ForeignKey(Photo, null=True, blank=True, on_delete=models.SET_NULL)
    custom_html = models.TextField(max_length=2000, verbose_name=_('Custom HTML'), null=True, blank=True)
    analytics_code = models.TextField(max_length=1000, verbose_name=_('Analytics code'), null=True, blank=True)

    template = models.CharField(_("Template"), max_length=200,
        choices=TEMPLATE_CHOICES, default=DEFAULT_TEMPLATE)

    license = models.CharField(_("License"), max_length=200,
        choices=LICENSE_CHOICES, default=DEFAULT_LICENSE)

    user = models.ForeignKey(user_model_name, verbose_name=_("Author"),
        related_name="%(class)ss", on_delete=models.CASCADE)

    room = models.ForeignKey(Room, blank=True, null=True, on_delete=models.SET_NULL)


    def get_photo(self):
        if self.header_image:
            return self.header_image
        else:
            try:
                return Photo.objects.get(slug=BLOG_PHOTO_SLUG + '-' + str(get_pattern(self.user)))
            except:
                return None

    def get_all_articles(self):
        from bitakora.base.models import Article
        return Article.objects.filter(blog=self)

    def get_articles(self):
        from bitakora.base.models import Article
        return Article.objects.published(for_blog=self)

    def get_articles_months(self):
        from bitakora.base.models import Article, CONTENT_STATUS_PUBLISHED
        month_list = Article.objects.filter(blog=self, status=CONTENT_STATUS_PUBLISHED).dates('publish_date', 'month', order='DESC')
        return month_list

    def get_myposts(self):
        from bitakora.base.models import Article
        return Article.objects.filter(blog=self).order_by('-publish_date')

    def get_comments(self):
        from bitakora.base.models import Comment
        articles = self.get_articles()
        return Comment.objects.filter(parent__in=articles)

    def get_last_comments(self):
        return self.get_comments()[:5]

    def get_external_links(self):
        from bitakora.base.models import External_link
        return External_link.objects.filter(blog=self).order_by("title")

    def get_blog_template(self):
        return "%s/%s/%s" % ("base", "css", self.template)

    def get_blog_categories(self):
        from bitakora.base.models import Category
        articles = self.get_articles()
        return Category.objects.filter(blogposts__in=articles)

    def get_absolute_url(self):
        return "/%s" % (self.slug)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Blog')
        verbose_name_plural = _('Blogs')


class Category(models.Model):
    title = models.CharField(_("Title"), max_length=500)
    slug = models.SlugField(_("URL"), max_length=2000, blank=True, null=True,
            help_text=_("Leave blank to have the URL auto-generated from "
                        "the title."))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        ordering = ("title",)

    # @models.permalink
    # def get_absolute_url(self):
    #     return ("blog_post_list_category", (), {"category": self.slug})


CONTENT_STATUS_DRAFT = 1
CONTENT_STATUS_PUBLISHED = 2
CONTENT_STATUS_CHOICES = (
    (CONTENT_STATUS_DRAFT, _("Draft")),
    (CONTENT_STATUS_PUBLISHED, _("Published")),
)


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name=_('Title'))
    slug = models.SlugField(_("URL"), max_length=2000, blank=True, null=True,
            help_text=_("Leave blank to have the URL auto-generated from "
                        "the title."))

    text = models.TextField(verbose_name=_('Text'))

    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

    status = models.IntegerField(_("Status"),
        choices=CONTENT_STATUS_CHOICES, default=CONTENT_STATUS_PUBLISHED,
        help_text=_("With Draft chosen, will only be shown for admin users "
            "on the site."))
    publish_date = models.DateTimeField(_("Published from"),
        help_text=_("With Published chosen, won't be shown until this time"),
        blank=True, null=True, db_index=True, default=now)
    expiry_date = models.DateTimeField(_("Expires on"),
        help_text=_("With Published chosen, won't be shown after this time"),
        blank=True, null=True)
    categories = models.ManyToManyField(Category,
                                        verbose_name=_("Categories"),
                                        blank=True, related_name="blogposts")
    allow_comments = models.BooleanField(verbose_name=_("Allow comments"),
                                         default=True)

    featured_image = models.ForeignKey(Photo, verbose_name=_("Featured Image"), null=True, blank=True, on_delete=models.SET_NULL)
    related_posts = models.ManyToManyField("self",
                                 verbose_name=_("Related posts"), blank=True)

    shared = models.BooleanField(default=False)

    objects = PublishedManager()

    def get_summary(self):
        return truncatechars(striptags(self.text), 600)

    def get_comments(self):
        return self.comments.all().order_by("publish_date")

    def get_visible_comments(self):
        return self.comments.filter(status=COMMENT_STATUS_VISIBLE).order_by("publish_date")

    def get_comments_count(self):
        return self.get_visible_comments().count()

    def is_editable(self, request):
        """
        Restrict in-line editing to the objects's owner and superusers.
        """
        return request.user.is_superuser or request.user.id == self.user_id

    def _get_next_or_previous_by_publish_date(self, is_next, **kwargs):
        """
        Retrieves next or previous object by publish date. We implement
        our own version instead of Django's so we can hook into the
        published manager and concrete subclasses.
        """
        arg = "publish_date__gt" if is_next else "publish_date__lt"
        order = "publish_date" if is_next else "-publish_date"
        lookup = {arg: self.publish_date}
        try:
            queryset = Article.objects.published
        except AttributeError:
            queryset = Article.objects.all
        try:
            return queryset(**kwargs).filter(**lookup).order_by(order)[0]
        except IndexError:
            pass

    def get_next_by_publish_date(self, **kwargs):
        """
        Retrieves next object by publish date.
        """
        return self._get_next_or_previous_by_publish_date(True, **kwargs)

    def get_previous_by_publish_date(self, **kwargs):
        """
        Retrieves previous object by publish date.
        """
        return self._get_next_or_previous_by_publish_date(False, **kwargs)

    def getTweetText(self):
        current_site = Site.objects.get_current()
        if self.blog.user.twitter_id:
            return "[%s] %s %s%s @%s" % (truncatechars(self.blog.name, 20), truncatechars(self.title, 40), current_site, self.get_absolute_url(), self.blog.user.twitter_id)
        return "[%s] %s %s%s" % (truncatechars(self.blog.name, 20), truncatechars(self.title, 50), current_site, self.get_absolute_url())

    def get_absolute_url(self):
        return reverse('article', kwargs={'blogslug': self.blog.slug, 'slug': self.slug})

    def save(self, *args, **kwargs):
        self.text = make_responsive(self.text)
        super(Article, self).save(*args, **kwargs)

    def get_rating(self):
        ctype = ContentType.objects.get_for_model(self)
        votes = Vote.objects.filter(object_id=self.id, content_type=ctype).count()
        comments = self.get_comments_count()
        return votes + comments

    def get_reverse_rating(self):
        return self.get_rating() * -1

    def get_timestamp(self):
        dtt = self.publish_date.timetuple()
        return time.mktime(dtt)

    def get_reverse_timestamp(self):
        return self.get_timestamp() * -1

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        ordering = ("-publish_date",)

COMMENT_STATUS_VISIBLE = 1

bitakora/templates/base/add_article.html
{% extends "base/base.html" %}
{% load i18n bootstrap %}

{% block header %}{% endblock %}

{% block extracss %}
    <link href="{{STATIC_URL}}js/select2/css/select2.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{{STATIC_URL}}css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block extrajs %}
    {{ form.media }}
    <script src="{{STATIC_URL}}js/select2/js/select2.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/select2/js/i18n/eu.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/moment.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/transition.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/collapse.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/bootstrap-datetimepicker.js"></script>
{% endblock %}

{% block body %}

<h1>{% block bodytitle %}{% trans 'New article' %}{% endblock %}</h1>

<form id="article_form" {% block form_url %}action="{% url 'add_article' blog.slug %}"{% endblock %} role="form" method="POST" ENCTYPE="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        {% if field.name == 'publish_date' %}
        <div class="col-sm-4">
            <div class="form-group">
                <label class="control-label  ">{{field.label}}</label>
                <div class='input-group date' id='id_publish_date'>
                    <input class="form-control" name="publish_date" value="{{field.value}}" type="text">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        {% elif field.name != 'featured_image' %}
        <div class="col-sm-12">
            {{field|bootstrap}}
        </div>
        {% else %}
            {% if article and article.featured_image %}
            <div class="col-sm-4">
                <img class="img-responsive" src="{{article.featured_image.get_related_url}}" alt="{{article.featured_image.title}}" title="{{article.featured_image.title}}"/>
            </div>
            {% endif %}
            <div class="col-sm-8">
            {{field|bootstrap}}
            </div>
        {% endif %}
    {% endfor %}
    <div class="col-sm-12">
      <div class="form-group">
        <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
      </div>
    </div>
</form>


{% block footer_js %}
  <script type="text/javascript">
    $('#id_categories').select2({
        language: "eu",
        placeholder: "{% trans 'Select or create new category' %}",
        minimumInputLength: 2,
        tags: true,
        ajax: {
            url: "{% url 'ajax_categories' %}",
            processResults: function (data) {
              return {
                results: data
              };
            }
        }
    });
    $('#id_related_posts').select2({
        language: "eu",
        minimumInputLength: 3,
        placeholder: "{% trans 'Select related articles' %}",
        ajax: {
            url: "{% url 'ajax_related_posts' %}",
            processResults: function (data) {
              return {
                results: data
              };
            }
        }
    });
    $('#id_publish_date').datetimepicker({locale: 'eu'});
  </script>
{% endblock %}




{% endblock %}

bitakora/templates/base/blog_archive.html
{% extends "base/blog_index.html" %}
{% load i18n l10n pagination_tags humanize %}

{% block title %}{% trans 'Archive' %} - {{blog.name}} - {% trans 'Bitakora' %}{% endblock %}

{% block blogcontent %}

<h2>{% trans 'Archive' %}</h2>
<ul>
    {% for date in blog.get_articles_months %}
    <li>
        <h4>{{date|date:"F"}}, {{date.year}}</h4>
        <ul class="list-unstyled">
            {% for art in articles %}
            {% if art.publish_date.year == date.year and art.publish_date.month == date.month %}
            <li><a href="{{art.get_absolute_url}}">{{art.title}}</a> ({{art.publish_date|date:"Y-m-d"}})</li>
            {% endif %}
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>

{% endblock %}

bitakora/templates/base/dashboard.html
{% extends "base/base.html" %}
{% load i18n bootstrap pagination_tags %}

{% block header %}{% endblock %}

{% block body %}

<h1>{% block bodytitle %}{% trans 'Dashboard' %}{% endblock %}</h1>

<ul class="nav nav-tabs" role="tablist">
	<li role="presentation" class="active"><a href="#articles" aria-controls="articles" role="tab" data-toggle="tab">{% trans "My articles" %}</a></li>
	<li role="presentation"><a href="{% url 'my_comments' user.get_blog.slug  %}" role="tab">{% trans "Comments" %}</a></li>
</ul>


<div class="tab-content">
    <div role="tabpanel" class="tab-pane {% if user.get_blog %}active{% endif %}" id="config">
		<table class="table table-striped">
			<thead>
				<th>{% trans 'Title' %}</th>
				<th>{% trans 'Status' %}</th>
				<th>{% trans 'Published from' %}</th>
				<th>{% trans 'Thumbnail' %}</th>
			</thead>
			<tbody>
				{% autopaginate blog.get_myposts 20 as posts %}
				{% for post in posts %}
				<tr>
					<td><a href="{% url 'article' post.blog.slug post.slug %}">{{post.title}}</a></td>
					<td>{{post.get_status_display}}</td>
					<td>{{post.publish_date}}</td>
					<td>{% if post.featured_image %}<img class="img-responsive" src="{{post.featured_image.get_admin_thumbnail_url}}" alt="{{post.featured_image.title}}" title="{{post.featured_image.title}}">{% endif %}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% paginate %}
	</div>
</div>
{% endblock %}

bitakora/templates/base/dashboard_comments.html
{% extends "base/base.html" %}
{% load i18n bootstrap pagination_tags %}

{% block header %}{% endblock %}

{% block body %}

<h1>{% block bodytitle %}{% trans 'Dashboard' %}{% endblock %}</h1>

<ul class="nav nav-tabs" role="tablist">
	<li role="presentation"><a href="{% url 'my_posts' user.get_blog.slug  %}" role="tab">{% trans "My articles" %}</a></li>
	<li role="presentation" class="active"><a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">{% trans "Comments" %}</a></li>
</ul>


<div class="tab-content">
    <div role="tabpanel" class="tab-pane {% if user.get_blog %}active{% endif %}" id="config">
		<table class="table table-striped">
			<thead>
				<th>{% trans 'Comment' %}</th>
				<th>{% trans 'User' %}</th>
				<th>{% trans 'Status' %}</th>
				<th>{% trans 'Published date' %}</th>
			</thead>
			<tbody>
				{% autopaginate blog.get_comments 20 as comments %}
				{% for comment in comments %}
				<tr>
					<td><a href="{% url 'article' comment.parent.blog.slug comment.parent.slug %}#{{comment.id}}">{{comment.text|striptags|truncatechars:"100"}}</a></td>
					<td>{% if comment.user %}{{comment.user.get_fullname}}{% else %}{{comment.nickname}}{% endif %}</td>
					<td>{{comment.get_status_display}} <a tabindex="0" data-toggle="popover" data-container="body" data-trigger="focus" data-title="{% trans 'Comment status' %}" data-content="<ul class='list-unstyled'><li><a href='{% url 'change_comment_status' %}?comment_id={{comment.id}}&status=1&next={{request.path}}'>{% trans 'Visible' %}</a></li><li><a href='{% url 'change_comment_status' %}?comment_id={{comment.id}}&status=2&next={{request.path}}''>{% trans 'Visible only for admin' %}</a></li><li><a href='{% url 'change_comment_status' %}?comment_id={{comment.id}}&status=3&next={{request.path}}''>{% trans 'Delete' %}</a></li></ul>" data-placement="left" data-html="true"><i class="glyphicon glyphicon-cog"></i></a></td>
					<td>{{comment.publish_date}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% paginate %}
	</div>
</div>

{% endblock %}

bitakora/templates/base/edit_article.html
{% extends "base/add_article.html" %}
{% load i18n %}

{% block bodytitle %}{% trans 'Edit article' %}{% endblock %}

{% block form_url %}action="{% url 'edit_article' blog.slug article.slug %}"{% endblock %}

bitakora/templates/base/new_blog.html
{% extends "base.html" %}
{% load i18n bootstrap %}

{% block header %}{% endblock %}

{% block extracss %}
    <link href="{{STATIC_URL}}js/lightbox/css/lightbox.css" rel="stylesheet">
{% endblock %}

{% block extrajs %}
    <script type="text/javascript" src="{{STATIC_URL}}js/tinymce/tinymce.min.js"></script>
{% endblock %}

{% block body %}

<h1>{% trans 'New blog' %}</h1>

{% if msg %}
  <div class="alert alert-warning" role="alert">
      <i class="glyphicon glyphicon-warning-sign"></i> {{ msg }}
  </div>
{% endif %}

<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#new" aria-controls="new" role="tab" data-toggle="tab">{% trans "Create from scratch" %}</a></li>
    <li role="presentation"><a href="#import" aria-controls="import" role="tab" data-toggle="tab">{% trans "Import from Wordpress" %}</a></li>
  </ul>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="new">
        <form action="{% url 'new_blog' %}" role="form" method="POST" ENCTYPE="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'header_image' %}
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="id_header_image" class="control-label ">{{field.label_tag}}</label>
                            <div class="row">
                                <div class="col-sm-12">
                                    <a href="{{user.get_blog_photo.get_configuration_url}}" data-lightbox="image-1" data-title="{% trans 'Header image' %}">
                                        <img class="img-responsive" src="{{user.get_blog_photo.get_configuration_url}}" alt="{{user.get_blog_photo.title}}" title="{{user.get_blog_photo.title}}" />
                                    </a>
                                </div>
                                <div class="col-sm-12">
                                  <p>{% trans 'This is your default header image. If you want to change it, select from your file system with the button below:' %}</p>
                                  <p>{{field}}</p>
                                  <p>{% trans 'Recommended sizes:' %}</p>
                                  <ul>
                                      <li>{% trans '1900x300px (horizontal)' %}</li>
                                      <li>{% trans '390x400px (vertical)' %}</li>
                                  </ul>
                                  <p>{{field.help_text}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% elif field.name == 'template' %}
                    <div class="col-sm-12">
                    		<div class="form-group">
                      			<label for="id_analytics_code" class="control-label  ">{% trans 'Template' %}</label>
                      			<div class="row">
                		            {% for radio in field %}
                		            <div class="col-sm-3">
                                    <a href="{{STATIC_URL}}img/templates/{{radio.choice_label|slugify}}.gif" data-lightbox="image-1" data-title="{{radio.choice_label}}">
                  		            	    <img class="img-responsive" src="{{STATIC_URL}}img/templates/{{radio.choice_label|slugify}}.gif" alt="{{radio.choice_label}}" title="{{radio.choice_label}}"/>
                                    </a>
                  		            	<p>{{radio}}</p>
                		            </div>
                		            {% endfor %}
                		        </div>
              	        </div>
            	      </div>
                {% elif field.name == 'license' %}
                <div class="col-sm-12">
                    <div class="form-group">
                        <label for="id_license" class="control-label  ">{% trans 'License' %}</label>
                        <ul>
                            {% for radio in field %}
                            <li class="list-unstyled">
                                {{radio}} {% if radio.choice_label == 'CC-BY-SA' %}(<a href="{% url 'about' %}#license">{% trans 'What is CC-BY-SA license?' %}</a>){% endif %}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                {% else %}
                    <div class="col-sm-12">
                        {{field|bootstrap}}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="col-sm-12">
              <div class="form-group">
                <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
              </div>
            </div>
        </form>
    </div>
    <div role="tabpanel" class="tab-pane" id="import">
        {% include 'base/import_new_blog.html' %}
    </div>
</div>

{% endblock %}

{% block sidebar %}{% endblock %}

{% block footerjs %}
    <script type="text/javascript" src="{{STATIC_URL}}js/lightbox/js/lightbox.js"></script>
{% endblock %}